@startuml

title __PGM's Class Diagram__\n

  namespace  {
    namespace tring.pgm {
      class String.pgm.IsUnique {
          {static} + isUnique()
          {static} + main()
          {static} - areAllCharUnique()
      }
    }
  }
  

  namespace  {
    namespace tring.pgm {
      class String.pgm.LeetCodeStringEasy {
          {static} + convertToLowrCase()
          {static} + main()
      }
    }
  }
  

  namespace  {
    namespace tring.pgm {
      class String.pgm.ReccuringCharsInStr {
          {static} + getReccurChar()
          {static} + getRecurringCharUsingHash()
          {static} - sort()
      }
    }
  }
  

  namespace  {
    namespace tring.pgm {
      class String.pgm.RemoveVowelFromStr {
          {static} + getRemoveVowel()
          {static} + main()
          {static} + removeVowelsFromStr()
      }
    }
  }
  

  namespace  {
    namespace tring.pgm {
      class String.pgm.ReverseStrWithChar {
          {static} + main()
          {static} + reverseString()
      }
    }
  }
  

  namespace  {
    namespace tring.pgm {
      class String.pgm.ReverseString {
          + reveseString()
      }
    }
  }
  

  namespace  {
    namespace tring.pgm {
      class String.pgm.SingleRowkeyboard {
          {static} + calculateTimeToTypeAWordWithOneFinger()
          {static} + main()
      }
    }
  }
  

  namespace  {
    namespace tring.pgm {
      class String.pgm.SplitStringIntoBalancedString {
          {static} + main()
          {static} - balancedStringSplit()
      }
    }
  }
  

  namespace  {
    namespace tring.pgm {
      class String.pgm.UniqueCharacterInString {
          {static} + uniqueIndex()
      }
    }
  }
  



right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
